spring:
  cloud:
    stream:
      function.definition: aggregate
      bindings:
        output:
          destination: transformed
        test-sink:
          destination: transformed
        input:
          destination: testtock
        test-source:
          destination: testtock
