spring:
    cloud.stream:
        bindings:
            input.destination: person-command
            output.destination: person-event
        kafka.binder.transaction:
            transaction-id-prefix: person-
            producer:
              configuration:
                retries: 1
                acks: all
    h2:
        console:
            settings:
                web-allow-others: true
            enabled: true
            path: /h2-console
    datasource:
        platform: ${UPA_DATABASE_PLATFORM:h2}
        url: ${UPA_DATABASE:jdbc:h2:tcp://localhost:1521/upaprocessor}
        username: ${UPA_DATABASE_USER:werkgever}
        password: ${UPA_DATABASE_PASSWORD:werkgever}
        driverClassName: ${UPA_DATABASE_DRIVER:org.h2.Driver}
    jpa.hibernate.ddl-auto: create-drop
server.port: 9998


